// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bigPanel': string;
  'button': string;
  'buttonActive': string;
  'controlPanel': string;
  'controlPanelContent': string;
  'controlPanelHead': string;
  'dropdown': string;
  'editorTitle': string;
  'editorTitleBar': string;
  'knobContainer': string;
  'pad': string;
  'padContainer': string;
  'padLabel': string;
  'padRow': string;
  'padSelected': string;
  'pulse': string;
  'pulseBg': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
